config/routes.rb
Server::Application.routes.draw do
  root to: "admin/dashboard#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :feed, only: [:show]
      resources :search, only: [:show]
      resources :device_tokens, only: [:create, :destroy]
      resources :followers, only: [:show]
      resources :is_friends, only: [:show]
      resources :attendees, only: [:show, :create, :update, :destroy]
      resources :friendships, only: [:show, :create, :destroy]
      resources :events, only: [:show, :create, :update, :destroy]
      resources :batch_attendees, only: [:create]
      resources :pending_events
      resources :owned_events
      resources :image_from_id
      get '/nearby_events', to: 'nearby_events#nearby'
      resources :users, except: :show
      get 'users/:uid', to: 'users#show'
      get '/events_attending', to: 'events#events_attending'
      post '/rsvp', to: 'attendees#rsvp'
    end
  end
  post '/admin/notifications',to: 'admin/notifications#notify'
end

app/views/admin/notifications/_new_notification.html.erb
<%= form_tag admin_notifications_path, method: 'post' do %>
  <p><%= label_tag 'Message to send to all users' %> </p>
  <%= text_field_tag :message, params[:message] %>
  <%= submit_tag("Send") %>
<% end %>
<br>
<br>
<br>
<%= form_tag admin_notifications_path, method: 'post' do %>
  <p><%= label_tag 'Message to send to user' %></p>
  <%= text_field_tag :message, params[:message] %>
  <p><%= label_tag 'Device Token' %></p>
<%= select_tag 'id', options_from_collection_for_select(User.all.each, 'id', 'username'), include_blank: 'All People' %>
  <%= submit_tag("Send") %>
<% end %>